"""Change Detail

Revision ID: 05f881e109a8
Revises: a060716389aa
Create Date: 2019-04-21 17:55:05.476445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f881e109a8'
down_revision = 'a060716389aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail', sa.Column('detail_tunmb', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_detail_detail_tunmb'), 'detail', ['detail_tunmb'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detail_detail_tunmb'), table_name='detail')
    op.drop_column('detail', 'detail_tunmb')
    # ### end Alembic commands ###
