"""add company

Revision ID: a060716389aa
Revises: 78c1fa92b432
Create Date: 2019-04-21 15:53:13.062444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a060716389aa'
down_revision = '78c1fa92b432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=140), nullable=False),
    sa.Column('company_type', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('promoimg', sa.String(length=120), nullable=True),
    sa.Column('companyname', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['companyname'], ['company.company_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo')
    op.drop_table('company')
    # ### end Alembic commands ###
